### ISSUE TITLE
[Bug] `last_checked` not updating in status

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#23]
http://status.ksp-ckan.space/

The Last Inflated and Last Indexed columns are working, but Last Checked seems to be only pulling forward values from the Perl bot:

![image](https://user-images.githubusercontent.com/1559108/64924360-56739f00-d7d3-11e9-87ca-bbd827ac8a64.png)

A code search for `last_checked` doesn't find anyplace where it's set.

Do we need it, though? It was always pretty redundant with `last_inflated`. Maybe we should remove it completely?

**Comment by techman83** [comment]
This is intentional. I'd always planned to do something with it, but never did. The place to update the status belongs in the scheduler code, but I didn't want to hold up release to add it. When we're doing things like skipping things with webhooks or doing timestamp checks on files/github apis, that's where this will come into play.

**Comment by techman83** [comment]
Thinking more on this, we should set it based off when the inflator does its bit. Because setting it during scheduling isn't technically correct and also would bump us up against the DynamoDB free tier rate limits. It will have an opportunity to become useful when start doing things when doing checks for changes based on API results or file change timestamps or skipping high frequency checks for mods with webhooks.
