### ISSUE TITLE
[Bug] Download counts also getting lost in git commit problems

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/NetKAN-Infra#36]
This is the most recent commit to update the download counts:

https://github.com/KSP-CKAN/CKAN-meta/commit/69712f9fe2728014bf0b3dc0b24069bc29e93a57

This is the current master version of the file

https://github.com/KSP-CKAN/CKAN-meta/blob/master/download_counts.json

The updates aren't there! Just take a look at the first few lines, they all match the 'before' part of the commit's diff rather than the 'after' part.

The new bot's commits are missing from the history:

https://github.com/KSP-CKAN/CKAN-meta/commits/master/download_counts.json

Something screwy is going on with git and the new bot.

This looks a lot like #33.

**Comment by techman83** [comment]
Yep it'll be related. Basically the full index run is the source of the truth, so when a merge conflict arises it'll win. The download count doesn't get updated, because the pull from master isn't doing anything and the bot is winning that argument. Which is why the commit is in the reflog, but not present in the branch.

It seems gitpython is a little unforgiving. Fortunately it's not causing anything _too_ nasty, so I think we can get by for now, but it really isn't ideal.

**Comment by HebaruSan** [comment]
There's no merge conflict here, though, because no one else updates that file. Isn't this because the upstream isn't being set?

**Comment by techman83** [comment]
Nope, but it isn't in its local history either. So the there is a conflict and it's winning.
