### ISSUE TITLE
[Bug] Staging process including extra commits

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/NetKAN-Infra#83]
Noted in KSP-CKAN/CKAN-meta#1530

**Comment by HebaruSan** [comment]
On closer inspection, I'm no longer sure anything really went wrong...

![image](https://user-images.githubusercontent.com/1559108/68817102-38e17b00-0646-11ea-92df-8887d6a07168.png)

Background:

- Staged mods within a given batch are processed last
- Staged mods are pushed immediately, and branched from whatever is in local master when we start processing the staged mod.
- Non-staged mods are pushed together in one group at the end of the batch.
- Pull requests list commits that are on their 'from' branch and not the 'to' branch.

Based on that, I think the available evidence is consistent with the following story in which everything works fine but there *appears* to be the *illusion* of a problem:

1. Start processing a batch of messages for StockSCANsat through CoolRockets (according to the above image)
2. Commit StockSCANsat through StockPlugins to master and let them sit there without pushing until we finish the batch
3. Create a branch for CoolRockets, which includes all of the previous commits from this pass
4. Commit the new CoolRockets version, push its staging branch, and create the pull request
5. GitHub takes a look at the staging branch and compares it to current master. Since we have not yet pushed the commits on master from step 2 to origin/master, they are not present on GitHub yet, so GitHub thinks they are part of the pull request, and they show up as such.
6. At the end of the batch, finally push master to GitHub, including all mods except CoolRockets
7. GitHub does not go back and revise the list of commits shown in the pull requests because it would be inefficient to do that for every open pull request every time there's a push
8. When we finally squash-merge, GitHub recognizes that some of the commits are redundant and ignores them, and ultimately only CoolRockets is added

If this is what happened, then there is no functional problem, but it is a little confusing for PR reviewers. An easy improvement might be to create the staging branches from origin/master instead of local master, so only the commits already on GitHub would be there.

**Comment by techman83** [comment]
I suspect that is what is going on. Due to the way the old bot worked, this happened "mid run" so master always had to be push/pulled before staging. 

I think an simpler fix could be to move the push to master from the context exit to just after processing the regular netkans. We already process staged secondary to regular ones.

**Comment by HebaruSan** [comment]
Yeah, that makes sense to me as well. Better to push a bit earlier than make the branch creation logic more complicated.
